name: CD:- Deploy

on:
  workflow_call:
  push:
    branches:
      - prod
      - stage

jobs:
  Deploy:
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
      AWS_REGION: ap-south-1
      SERVICE_NAME: back-office
      DEPLOYMENT_BUCKET: back-office-deployment-bucket

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 16
      - name: Install serverless dependency
        run: yarn install --frozen-lockfile
      - name: Inject slug/short variables
        uses: rlespinasse/github-slug-action@v3.x
      - name: Package Stack
        run: npx serverless package
        env:
          STAGE: ${{ env.GITHUB_REF_SLUG }}
      - name: Deploy Stack
        run: npx serverless deploy --package .serverless
        env:
          STAGE: ${{ env.GITHUB_REF_SLUG }}
